services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - transmission
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_DIR=/app/data
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission:latest
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - USER=admin
      - PASS=secret123
    volumes:
      - ./downloads:/downloads
      - ./transmission-config:/config
    restart: unless-stopped

volumes:
  downloads:
  data:
  transmission-config: